INSERT INTO book_category VALUES ('ALB', 'Albumy');
INSERT INTO book_category VALUES ('AUD', 'Audiobooki');
INSERT INTO book_category VALUES ('BIO', 'Biografie');
INSERT INTO book_category VALUES ('BIZ', 'Biznes, ekonomia');
INSERT INTO book_category VALUES ('DZI', 'Dla dzieci');
INSERT INTO book_category VALUES ('MLO', 'Dla młodzieży');
INSERT INTO book_category VALUES ('ENC', 'Encyklopedie');
INSERT INTO book_category VALUES ('FAN', 'Fantastyka');
INSERT INTO book_category VALUES ('FIL', 'Filozofia');
INSERT INTO book_category VALUES ('HIS', 'Historia');
INSERT INTO book_category VALUES ('INF', 'Informatyka');
INSERT INTO book_category VALUES ('JEZ', 'Językoznawstwo');
INSERT INTO book_category VALUES ('KAL', 'Kalendarze');
INSERT INTO book_category VALUES ('KOM', 'Komiks');
INSERT INTO book_category VALUES ('KUC', 'Kuchnia i diety');
INSERT INTO book_category VALUES ('LIT', 'Literatura');
INSERT INTO book_category VALUES ('FAK', 'Literatura faktu');
INSERT INTO book_category VALUES ('OBY', 'Literatura obycz.');
INSERT INTO book_category VALUES ('NAU', 'Nauka języków');
INSERT INTO book_category VALUES ('SCI', 'Nauki ścisłe');
INSERT INTO book_category VALUES ('POD', 'Podręczniki');
INSERT INTO book_category VALUES ('POR', 'Poradniki');
INSERT INTO book_category VALUES ('PRA', 'Prawo');
INSERT INTO book_category VALUES ('PSY', 'Psychologia');
INSERT INTO book_category VALUES ('REL', 'Religie i wyznania');
INSERT INTO book_category VALUES ('ROM', 'Romans');
INSERT INTO book_category VALUES ('ROZ', 'Rozwój osobisty');
INSERT INTO book_category VALUES ('SEN', 'Sensacja, kryminał');
INSERT INTO book_category VALUES ('SOC', 'Socjologia');
INSERT INTO book_category VALUES ('SPO', 'Sport i wypoczynek');
INSERT INTO book_category VALUES ('SZT', 'Sztuka');
INSERT INTO book_category VALUES ('THR', 'Thriller, horror');
INSERT INTO book_category VALUES ('TUR', 'Turystyka i podróże');
INSERT INTO book_category VALUES ('ZDR', 'Zdrowie, rodzina');