INSERT INTO book( author , deleted , description , pages , quantity, title , unit_price , year , category_id)
VALUES ('TESTA',FALSE,'TESTD',111,100,'TESTT',120.5 , 2015, 'TST');
INSERT INTO book_rating(comment , nick , rating_date , rating , book_id) values ('TESTC' , 'TESTN' , current_date , 1 , 1);
INSERT INTO customer_message(customer_email , date , message) values ('test@test.pl' , current_date , 'testm');

INSERT INTO book_category VALUES ('ALB', 'Albumy');
INSERT INTO book_category VALUES ('AUD', 'Audiobooki');
INSERT INTO book_category VALUES ('BIO', 'Biografie');
INSERT INTO book_category VALUES ('BIZ', 'Biznes, ekonomia, marketing');
INSERT INTO book_category VALUES ('DZI', 'Dla dzieci');
INSERT INTO book_category VALUES ('MLO', 'Dla młodzieży');
INSERT INTO book_category VALUES ('ENC', 'Encyklopedie, leksykony');
INSERT INTO book_category VALUES ('FAN', 'Fantastyka');
INSERT INTO book_category VALUES ('FIL', 'Filozofia');
INSERT INTO book_category VALUES ('HIS', 'Historia');
INSERT INTO book_category VALUES ('INF', 'Informatyka');
INSERT INTO book_category VALUES ('JEZ', 'Językoznawstwo, język polski');
INSERT INTO book_category VALUES ('KAL', 'Kalendarze');
INSERT INTO book_category VALUES ('KOM', 'Komiks');
INSERT INTO book_category VALUES ('KUC', 'Kuchnia i diety');
INSERT INTO book_category VALUES ('LIT', 'Literatura');
INSERT INTO book_category VALUES ('FAK', 'Literatura faktu');
INSERT INTO book_category VALUES ('OBY', 'Literatura obyczajowa');
INSERT INTO book_category VALUES ('NAU', 'Nauka języków');
INSERT INTO book_category VALUES ('SCI', 'Nauki ścisłe, medycyna');
INSERT INTO book_category VALUES ('POD', 'Podręczniki szkolne, edukacja');
INSERT INTO book_category VALUES ('POR', 'Poradniki');
INSERT INTO book_category VALUES ('PRA', 'Prawo');
INSERT INTO book_category VALUES ('PSY', 'Psychologia i pedagogika');
INSERT INTO book_category VALUES ('REL', 'Religie i wyznania');
INSERT INTO book_category VALUES ('ROM', 'Romans');
INSERT INTO book_category VALUES ('ROZ', 'Rozwój osobisty, motywacja');
INSERT INTO book_category VALUES ('SEN', 'Sensacja, kryminał');
INSERT INTO book_category VALUES ('SOC', 'Socjologia');
INSERT INTO book_category VALUES ('SPO', 'Sport i wypoczynek');
INSERT INTO book_category VALUES ('SZT', 'Sztuka');
INSERT INTO book_category VALUES ('THR', 'Thriller, horror');
INSERT INTO book_category VALUES ('TUR', 'Turystyka i podróże');
INSERT INTO book_category VALUES ('ZDR', 'Zdrowie, rodzina, związki');